pipeline {
    agent none

    stages {
        stage('Info about tool') {
            agent {
                node {
                    label 'test'
                }
            }
            tools {
                maven 'tool-apache-maven-3.6.3' 
            }
            steps {
                echo 'Current node'
                sh 'hostname'

                echo 'Current working directory: '
                sh 'pwd'

                echo 'List of files: '
                sh 'ls -la'

                echo 'Maven version: '
                sh 'mvn --version'
            }
        }
        stage('Docker with Maven') {
            agent { 
                docker { 
                    image 'maven:3-alpine' 
                    label 'test'
                }
            } 
            steps {
                echo 'Hello, Maven'
                sh 'mvn --version'
            }
        }
        stage('Docker with Java') {
            agent { 
                docker {
                    image 'openjdk:8-jre' 
                    label 'test'
                }
            }
            steps {
                echo 'Hello, JDK'
                sh 'java -version'
            }
        }
        stage('Dockerfile with Python') {
            agent { 
                dockerfile {
                    filename 'Dockerfile'
                    dir 'pipelines/syntax-exercises'
                    label 'test'
                    additionalBuildArgs '--build-arg version=1.0.2'
                    args '-v /tmp:/tmp'
                }
            }
            steps {
                echo 'Hello, Python'
                sh 'python --version'
            }
        }
    }
}