pipeline {
    agent none

    stages {
        stage('Info') {
            steps {
                echo 'Current working directory: '

                sh 'pwd'

                echo 'List of files: '

                sh 'ls -la'
            }
        }
        stage('Acceptance tests') {
            agent {
                node {
                    label 'homelab'
                }
            }
            steps {
                echo 'Checkout code from GitLab...'

                checkout([$class: 'GitSCM', branches: [[name: '*/master']], browser: [$class: 'GitLab', repoUrl: 'http://192.168.0.18:9080'], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '4136d7ee-8c32-4f18-ad19-0db3d1d93df1', url: 'http://192.168.0.18:9080/seba/simple-rest-api-python-flask.git']]])

                echo 'Current working directory: '

                sh 'pwd'

                echo 'List of files: '

                sh 'ls -la'

                echo 'Acceptance testing..'

                sh 'robot --outputdir results atest/'
            }
            post {
                always {
                    step([
                        $class : 'RobotPublisher',
                        outputPath : 'results',
                        outputFileName : 'output.xml',
                        reportFileName : 'report.html',
                        logFileName : 'log.html',
                        disableArchiveOutput : false,
                        passThreshold : 100,
                        unstableThreshold: 95.0,
                        otherFiles : '',
                    ])
                }
            }
        }
    }
}