pipeline {
    agent {
        docker {
            image 'maven:3.6.3-jdk-11'
            args '-v /root/.m2:/root/.m2'
        }
    }

    stages {
        stage('Info') {
            steps {
                echo 'Current working directory: '

                sh 'pwd'

                echo 'List of files: '

                sh 'ls -la'
            }
        }
        stage('Checkout') {
            steps {
                echo 'Checkout code from GitLab...'

                checkout([$class: 'GitSCM', branches: [[name: '*/master']], browser: [$class: 'GitLab', repoUrl: 'http://192.168.0.18:9080'], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '4136d7ee-8c32-4f18-ad19-0db3d1d93df1', url: 'http://192.168.0.18:9080/seba/simple-rest-api-java-spring.git']]])

                echo 'Current working directory: '

                sh 'pwd'

                echo 'List of files: '

                sh 'ls -la'
            }
        }        
        stage('Code analysis') {
            steps {
                withSonarQubeEnv('SonarQube Server') {
                    // Optionally use a Maven environment you've configured already
//                     withMaven(maven:'Maven 3.5') {
                        sh 'mvn clean package sonar:sonar'
//                     }
                }
            }
        }
        stage("Quality gate") {
            steps {
                timeout(time: 3, unit: 'MINUTES') {
                    // Parameter indicates whether to set pipeline to UNSTABLE if Quality Gate fails
                    // true = set pipeline to UNSTABLE, false = don't
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }

    post {
        success {
            mail to: "sebaczech@gmail.com",
            subject: "CI/CD platform - success pipeline - ${currentBuild.fullDisplayName}",
            body: "Everything is ok with ${env.BUILD_URL}"
        }
        failure {
            mail to: "sebaczech@gmail.com",
            subject: "CI/CD platform - failed pipeline: ${currentBuild.fullDisplayName}",
            body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
}