version: '3'
services:
  nodejs:
    build: .
    container_name: web_app
    ports:
      - "32128:3000"
    networks:
      - nginx-proxy-network
  webserver:
    image: nginx:mainline-alpine
    container_name: simple_web_server
    restart: unless-stopped
    ports:
      - "48080:80"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
    networks:
      - nginx-proxy-network
networks:
  nginx-proxy-network:
    driver: bridge