apiVersion: v1
kind: Service
metadata:
  name: api-java-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    role: api-java
  ports:
    - protocol: TCP
      port: 32080
      targetPort: 48080
