apiVersion: v1
kind: Service
metadata:
  name: api-java-service
spec:
  type: NodePort
  selector:
    role: api-java
  ports:
    - protocol: TCP
      port: 32080
      targetPort: 48080
      nodePort: 38080
