pipeline {
    agent {
        node {
            label 'homelab'
        }
    }

    stages {
        stage('Info') {
            steps {
                echo 'Current working directory: '

                sh 'pwd'

                echo 'List of files: '

                sh 'ls -la'
            }
        }
        stage('Docker Swarm deploy app') {
            steps {
                sh 'ansible-playbook -i playbooks/hosts.yml playbooks/playbook-docker-swarm.yml'
            }
        }
    }

    post {
        success {
            mail to: "sebaczech@gmail.com",
            subject: "CI/CD platform - success pipeline - ${currentBuild.fullDisplayName}",
            body: "Everything is ok with ${env.BUILD_URL}"
        }
        failure {
            mail to: "sebaczech@gmail.com",
            subject: "CI/CD platform - failed pipeline: ${currentBuild.fullDisplayName}",
            body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
}