version: '3'
services:
  webapp:
    build: .
    container_name: web_app
    ports:
      - "58080:48080"
    networks:
      - nginx-proxy-network
  webserver:
    image: 192.168.0.18:5000/api-java:cicd
    container_name: api-java
    restart: unless-stopped
    ports:
      - "68080:80"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp
    networks:
      - nginx-proxy-network
networks:
  nginx-proxy-network:
    driver: bridge