version: '3'
services:
  webapp:
    # build: .
    image: 192.168.0.18:5000/api-java:cicd
    container_name: web-app
    # ports:
    #  - "58080:48080"
    networks:
      - nginx-proxy-network
  webserver:
    image: nginx:mainline-alpine
    container_name: web-server
    restart: unless-stopped
    ports:
      - "28080:80"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - webapp
    networks:
      - nginx-proxy-network
networks:
  nginx-proxy-network:
    driver: bridge