---
- hosts: devops
  tasks:  
    - name: Get a list of all pods from any namespace
      k8s_info:
        kind: Pod
      register: pod_list
    - name: Show list of pods
      debug:
        var: item
      loop: "{{ pod_list | json_query('resources[*].metadata.name') }}"
    - name: Create a service object by reading the definition from a file
      k8s:
        state: present
        definition: "{{ lookup('file', 'kubernetes/api-java/service-loadbalancer.yml') }}"
    - name: Create a deployment object by reading the definition from a file
      k8s:
        state: present
        definition: "{{ lookup('file', 'kubernetes/api-java/deployment.yml') }}"
        