---
- name: Install SonarQube
  hosts: homelab
  vars:
    DOCKER_VOLUMES:
      - sonarqube_data
      - sonarqube_extensions
      - sonarqube_logs
  tasks:  
  - name: Create a volumes in Docker
    docker_volume:
      name: "{{ item }}"
    loop: "{{ DOCKER_VOLUMES }}"
  - name: Start Docker container for SonarQube
    docker_container:
      name: sonar-qube
      image: sonarqube:latest
      hostname: devops
      ports:
        - "9000:9000"
      volumes:
        - sonarqube_extensions:/opt/sonarqube/extensions
        - sonarqube_logs:/opt/sonarqube/logs
        - sonarqube_data:/opt/sonarqube/data