# https://docs.docker.com/registry/deploying/
---
- name: Install Docker Registry
  hosts: homelab
  
  tasks:
  - name: Start Docker Registry
    docker_container:
      name: registry
      image: registry:2
      hostname: devops
      restart_policy: always    
      ports:
        - "443:443"
      env:
        REGISTRY_HTTP_ADDR: "0.0.0.0:443"
        REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/domain.crt"
        REGISTRY_HTTP_TLS_KEY: "/certs/domain.key"
      volumes:
        - /home/seba/certs:/certs
  - name: Copy file with Docker daemon settings
    copy:
      src: ../configurations/daemon.json
      dest: /etc/docker/daemon.json
    become: yes
  - name: Creates directory certs.d
    file:
      path: /etc/docker/certs.d/
      state: directory    
    become: yes
  - name: Creates directory 192.168.0.27
    file:
      path: /etc/docker/certs.d/192.168.0.27
      state: directory    
    become: yes  
  - name: Copy file with cert
    copy:
      src: /home/seba/certs/domain.crt
      dest: /etc/docker/certs.d/192.168.0.27/ca.crt
      remote_src: yes
    become: yes     
  - name: Copy file with cert to remote machine
    command: "scp /home/seba/certs/domain.crt devops:/tmp/ca-192.168.0.27.crt"
    register: scp_out
  - name: Show scp results
    debug: var={{item}}
    with_items: scp_out.stdout_lines  
  - name: Create dir on remote machine
    command: "ssh devops sudo mkdir -p /etc/docker/certs.d/192.168.0.27"
    register: mkdir_out
  - name: Show mkdir results
    debug: var={{item}}
    with_items: mkdir_out.stdout_lines       
  - name: Move file with cert to remote machine
    command: "ssh devops sudo mv /tmp/ca-192.168.0.27.crt /etc/docker/certs.d/192.168.0.27/ca.crt"
    register: mv_out
  - name: Show mv results
    debug: var={{item}}
    with_items: mv_out.stdout_lines     
  - name: Copy file with cert on remote machine
    command: "ssh devops sudo cp /etc/docker/certs.d/192.168.0.27/ca.crt /usr/local/share/ca-certificates/kubernetes.crt"
    register: cp_out
  - name: Show cp results
    debug: var={{item}}
    with_items: cp_out.stdout_lines     
  - name: Update certificates on remote machine
    command: "ssh devops sudo update-ca-certificates"
    register: update_ca_out
  - name: Show update results
    debug: var={{item}}
    with_items: update_ca_out.stdout_lines     
  - name: Restart service Docker, in all cases
    service:
      name: docker
      state: restarted
    become: yes
