---
- name: Install Jenkins 
  hosts: homelab
  tasks:  
    - name: Add key
      shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
      ignore_errors: True
      become: yes
    - name: Add source list
      shell: sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
      ignore_errors: True
      become: yes
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600  
      become: yes
    - name: Install Java
      package:
        name: openjdk-11-jdk
        state: present      
      become: yes
    - name: Install Jenkins
      package:
        name: jenkins
        state: present      
      become: yes