---
- name: Install GitLab
  hosts: devops
  vars:
    DOCKER_PACKAGES:
      - requests
      - docker
    DOCKER_VOLUMES:
      - gitlab-data
      - gitlab-config
      - gitlab-logs
  tasks:  
  - name: Download pip
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: ~/get-pip.py
      mode: 0755
  - name: Install pip
    shell: python get-pip.py
    register: pip_install
    become: yes
  - name: Show pip installation
    debug: var={{item}}
    with_items: pip_install.stdout_lines            
  - name: Install pip packages required for Docker
    pip:
      name: "{{ item }}"
    loop: "{{ DOCKER_PACKAGES }}"
  - name: Create a volumes in Docker
    docker_volume:
      name: "{{ item }}"
    loop: "{{ DOCKER_VOLUMES }}"
  - name: Start Docker container for GitLab
    docker_container:
      name: gitlab
      image: gitlab/gitlab-ce:latest 
      hostname: devops
      ports:
        - "9443:443"
        - "9080:80"
        - "2022:22"
      volumes:
        - gitlab-config:/etc/gitlab
        - gitlab-logs:/var/log/gitlab
        - gitlab-data:/var/opt/gitlab
