---
- hosts: devops
  tasks:  
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600  
      become: yes
    - name: Install zsh
      package:
        name: zsh
        state: present      
      become: yes
    - name: Copy file with ZSH settings
      copy:
        src: ../configurations/.zshrc
        dest: ~/.zshrc
        owner: seba
        group: seba
        mode: '0600'